ls
version: "3.9"
services:
    backend:
        image: countries
        container_name: countries
        build:
            context: ./countries
        ports:
            - "9000:80"
    frontend:
        image: countries-ui
        container_name: countries-ui
        build:
            context: countries-ui
        ports:
            - "4200:80"
        depends_on:
            - backend    